# The URL the site will be built for
base_url = "https://jan.systems"

title = "Jan Tuomi"
description = "Minimalist, digital gardener, senior software engineer."
default_language = "en"
generate_feeds = true
feed_filenames = ["atom.xml"]
author = "Jan Tuomi"
generate_sitemap = true
generate_robots_txt = true
compile_sass = false
build_search_index = false

taxonomies = [{ name = "kind", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
error_on_missing_highlight = true
external_links_target_blank = true
bottom_footnotes = true
lazy_async_image = false
insert_anchor_links = "heading"

[extra]
# Put all your custom variables here
